### ISSUE TITLE
make url-rewrite with "-" for spaces

### ISSUE THREAD

**Issue by NotWes** [NotWes/Growconomy#3]

**Comment by MatteuGT** [comment]
what do you mean by "make url-rewrite with "-" for spaces"?

**Comment by NotWes** [comment]
For example https://www.growconomy.net/item/Dirt Block
needs to be https://www.growconomy.net/item/Dirt-Block

**Comment by MatteuGT** [comment]
str_replace function?

**Comment by NotWes** [comment]
Done.
